[workspace]
members = [
    "crates/core",
    "crates/http",
    "crates/macros",
    "crates/runtime",
    "crates/allora",
    "examples/basic/helloworld",
    "examples/basic/http-inbound",
    "examples/basic/http-outbound"
]
resolver = "2"

[workspace.package]
version = "0.0.2"
edition = "2021"
license = "Apache-2.0"
authors = ["Allora Contributors"]
repository = "https://github.com/fialucci/allora"
homepage = "https://github.com/fialucci/allora"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
uuid = { version = "1.8", features = ["v4"] }
async-trait = "0.1"
allora-runtime = { path = "crates/runtime" }
allora = { path = "crates/allora" }

[patch.crates-io]
# (optional) override if publishing internal crates later
