[package]
name = "allora-http-inbound-example"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Allora Contributors"]
publish = false

[dependencies]
allora = { path = "../../../crates/allora" }
allora-runtime = { path = "../../../crates/runtime" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features=["fmt", "env-filter"] }
tokio = { version = "1.39", features=["rt-multi-thread", "macros", "sync", "signal" ] }
hyper = { version = "0.14", features=["full"] }
async-trait = "0.1"
inventory = "0.3"
