[package]
name = "allora"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "allora"
path = "src/lib.rs"

[dependencies]
allora-core = { path = "../core" }
allora-runtime = { path = "../runtime" }
allora-http = { path = "../http" }
allora-macros = { path = "../macros" }
inventory = "0.3"
