//! ServiceActivator trait: metadata & channel binding intent for a service (activator).
//! Service trait: pure processing logic over an Exchange (business logic only).
//!
//! A Service consumes an `Exchange` from a source ("from" channel), applies processing logic
//! implemented by the user (transforming headers, body, or producing an outbound message), and
//! then conceptually publishes the result to a target ("to" channel). The concrete routing /
//! dispatch to channels is orchestrated outside this trait; implementers focus solely on
//! transforming the provided `Exchange`.
//!
//! # Goals
//! * Provide a stable interface for custom service implementations (sync or async).
//! * Keep signature minimal: a single `process` (or `process_async`) plus metadata accessors.
//! * Avoid prescribing how channel dispatch happens; separation of concerns with builders / runtime.
//!
//! # Async Feature
//! With the `async` feature enabled the trait exposes `async fn process(...)`. Without it a
//! synchronous `fn process(...)` is used. This mirrors the pattern employed by the `Processor`
//! trait in `processor.rs`.
//!
//! # Metadata Accessors
//! * `id()` – stable identifier (auto-generated or user supplied).
//! * `from()` / `to()` – declared channel ids for wiring.
//! * `ref_name()` – reference name matching YAML `ref-name` and the `#[service(name=..)]` macro argument (not a file path).
//!
//! # Implementing
//! ```ignore
//! use allora::{service::Service, Exchange, error::Result};
//! struct UppercaseService;
//! impl UppercaseService { pub fn new() -> Self { Self } }
//! #[cfg_attr(feature = "async", async_trait::async_trait)]
//! impl Service for UppercaseService {
//!     #[cfg(feature = "async")]
//!     async fn process(&self, exchange: &mut Exchange) -> Result<()> {
//!         if let Some(body) = exchange.in_msg.body_text() { exchange.in_msg.set_body_text(body.to_uppercase()); }
//!         Ok(())
//!     }
//!     #[cfg(not(feature = "async"))]
//!     fn process(&self, exchange: &mut Exchange) -> Result<()> {
//!         if let Some(body) = exchange.in_msg.body_text() { exchange.in_msg.set_body_text(body.to_uppercase()); }
//!         Ok(())
//!     }
//! }
//! ```
//! (Single impl with conditional methods; avoids duplication.)
//!
//! # Future Extensions
//! * Error classification (e.g. routing vs transformation).
//! * Lifecycle hooks (`init`, `shutdown`).
//! * Metrics instrumentation via feature flag.
//!
//! This file intentionally provides only the trait; concrete implementations are user-defined
//! or generated by a future service builder.

use crate::{error::Result, Exchange};
use std::fmt::Debug;

/// Internal metadata describing how a service is wired. Users do NOT implement this directly; it is derived from specs.
pub trait ServiceActivator: Send + Sync + Debug {
    fn id(&self) -> &str;
    fn from(&self) -> &str;
    fn to(&self) -> &str;
    fn ref_name(&self) -> &str;
}

#[cfg_attr(feature = "async", async_trait::async_trait)]
pub trait Service: Send + Sync + Debug {
    #[cfg(not(feature = "async"))]
    fn process(&self, exchange: &mut Exchange) -> Result<()>;
    #[cfg(feature = "async")]
    async fn process(&self, exchange: &mut Exchange) -> Result<()>;
    #[cfg(not(feature = "async"))]
    fn process_sync(&self, exchange: &mut Exchange) -> Result<()> {
        self.process(exchange)
    }
    #[cfg(feature = "async")]
    fn process_sync(&self, exchange: &mut Exchange) -> Result<()> {
        let handle = match tokio::runtime::Handle::try_current() {
            Ok(h) => h,
            Err(_) => {
                return Err(crate::error::Error::other(
                    "process_sync (async mode) requires a Tokio runtime; wrap calls in #[tokio::main] or create a Runtime",
                ))
            }
        };
        tokio::task::block_in_place(|| handle.block_on(async { self.process(exchange).await }))
    }
}
